### ISSUE TITLE
Logs not printing through golang console and server not controllable - dumb-init issue?

### ISSUE THREAD

**Issue by willnwalker** [ghostlydilemma/openttd-jgrpp#3]
When using the provided `docker-compose.yaml` file with Docker Desktop on Windows using WSL 2 backend the below config no longer proxies server messages to the console and the console cannot be used to change settings on the running OpenTTD server within its separate container.

```
version: '3'
services:
    openttd:
        image: ghcr.io/ghostlydilemma/openttd-jgrpp:0.54.4
        ports:
            - "3979:3979/tcp"
            - "3979:3979/udp"
        volumes:
            - "//c/Users/<user>/Documents/OpenTTD:/home/openttd/.local/share/openttd/"
        restart: always
        environment:
            PUID: "1000"
            PGID: "1000"
            loadgame: last-autosave

    console:
            image: golang
            command: sleep infinity
```

The process and group user IDs were that of my WSL 2 user, and the Docker Desktop service was re-registered and verified.

Docker Engine v24.0.5
